server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# DB \uC124\uC815 (Supabase PostgreSQL)
#jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.qoxppyvvqtendjlxpgco&password=[YOUR-PASSWORD]
# 1. \uC811\uC18D \uC8FC\uC18C (URL) - \uB4A4\uC5D0 \uC635\uC158\uC744 \uBD99\uC5EC\uC8FC\uB294 \uAC8C \uC88B\uC544!
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# 2. \uC0AC\uC6A9\uC790 \uC774\uB984 (Username)
spring.datasource.username=postgres.qoxppyvvqtendjlxpgco

# 3. \uBE44\uBC00\uBC88\uD638 (Password) - \uAC00\uB839\uC774\uAC00 \uC124\uC815\uD55C \uBE44\uBC00\uBC88\uD638 \uADF8\uB300\uB85C!
spring.datasource.password=igarung7297@gmail


#spring.datasource.url=jdbc:postgresql://db.qoxppyvvqtendjlxpgco.supabase.co:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=igarung7297@gmail


spring.datasource.driver-class-name=org.postgresql.Driver

# JPA \uBC0F Hibernate \uC124\uC815 (\uC774 \uBD80\uBD84\uC774 \uAF2D \uD544\uC694\uD574!) # spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



# \uC11C\uBC84 \uD3EC\uD2B8 \uBC0F \uAE30\uD0C0 \uC124\uC815
server.port=8080
file.upload-root=upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB