server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# DB \uC124\uC815 (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.qoxppyvvqtendjlxpgco.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=igarung7297@gmail
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA \uBC0F Hibernate \uC124\uC815 (\uC774 \uBD80\uBD84\uC774 \uAF2D \uD544\uC694\uD574!) # spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# \uC11C\uBC84 \uD3EC\uD2B8 \uBC0F \uAE30\uD0C0 \uC124\uC815
server.port=8080
file.upload-root=upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB